name: RSpec CI

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - '*-maintenance'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  docs:
    uses: rspec/rspec/.github/workflows/documentation_coverage.yml@main

  rubocop:
    uses: rspec/rspec/.github/workflows/rubocop.yml@main

  core:
    uses: rspec/rspec/.github/workflows/rspec.yml@main
    with:
      library: 'rspec-core'
      rspec_version: '= 3.14.0.pre'

  mocks:
    uses: rspec/rspec/.github/workflows/rspec.yml@main
    with:
      library: 'rspec-mocks'
      rspec_version: '= 3.14.0.pre'

  expectations:
    uses: rspec/rspec/.github/workflows/rspec.yml@main
    with:
      library: 'rspec-expectations'
      rspec_version: '= 3.14.0.pre'

  support:
    uses: rspec/rspec/.github/workflows/rspec.yml@main
    with:
      library: 'rspec-support'
      rspec_version: '= 3.14.0.pre'
